services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rag_sqlserver_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Password123!
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G

volumes:
  sqldata:
